---
title: "Water Chemistry Analysis"
author: "Samuel Dumas"
date: "Winter Semester 2024"
---

```{r}
library(tidyverse)
library(dplyr)
library(lme4)
library(ggpubr)
library(vegan)
library(gtools)
```
# Global

```{r}
PONDS <- c("T106A1", "T106A2", "T106A3", "T106B1", "T106B2", "T106B3",
           "T108A1", "T108A2", "T108A3", "T108B1", "T108B2", "T108B3",
           "T109A1", "T109A2", "T109A3", "T109B1", "T109B2", "T109B3")
```


# Water Chemistry

```{r}
verticalData <- read_csv("Urban_Stream_2023_Site_Sample_Data_VP.csv")
```

```{r}
head(verticalData)
```

```{r}
pondIDs <- c("T106", "T108", "T109")
verticalSubData <- verticalData %>% 
  subset(Pond %in% pondIDs & Depth < 160)

numLabs <- c("July", "August")
names(numLabs) <- c("1", "2")
```


## GRAPHS

```{r Temperature}
meanTempData <- verticalSubData %>% 
  group_by(Depth) %>%
  mutate(meanTemp = mean(Temperature))

verticalSubData %>% 
  ggplot(aes(x = Depth, y = Temperature, group = Pond, colour = Pond)) +
   geom_line(data = meanTempData, aes(x = Depth, y = meanTemp), 
             colour = "black",
             linetype = "longdash") +
  geom_line() +
  geom_point() +
  facet_wrap(vars(Num), labeller = labeller(Num = numLabs))
```

```{r}
meanDoData <- verticalSubData %>% 
  group_by(Depth) %>%
  mutate(meanDo = mean(DO))

verticalSubData %>% 
  ggplot(aes(x = Depth, y = DO, group = Pond, colour = Pond)) +
   geom_line(data = meanDoData, aes(x = Depth, y = meanDo), 
             colour = "black",
             linetype = "longdash") +
  geom_line() +
  geom_point() +
  facet_wrap(vars(Num), labeller = labeller(Num = numLabs))
```

```{r}
meanCondData <- verticalSubData %>% 
  group_by(Depth) %>%
  mutate(meanCond = mean(Conductivity))

verticalSubData %>% 
  ggplot(aes(x = Depth, y = Conductivity, group = Pond, colour = Pond)) +
   geom_line(data = meanCondData, aes(x = Depth, y = meanCond), 
             colour = "black",
             linetype = "longdash") +
  geom_line() +
  geom_point() +
  facet_wrap(vars(Num), labeller = labeller(Num = numLabs))
```

```{r}
meanTurbData <- verticalSubData %>% 
  group_by(Depth) %>%
  mutate(meanTurb = mean(Turbidity))

verticalSubData %>% 
  ggplot(aes(x = Depth, y = Turbidity, group = Pond, colour = Pond)) +
   geom_line(data = meanTurbData, aes(x = Depth, y = meanTurb), 
             colour = "black",
             linetype = "longdash") +
  geom_line() +
  geom_point() +
  facet_wrap(vars(Num), labeller = labeller(Num = numLabs))
```

## LINEAR MODELS

```{r}
tempDepthModel1 <- lm(Temperature ~ Depth, verticalSubData)
summary(tempDepthModel1)

tempDepthModel <- function(pondID,
                           num){
  tempModel <- lm(Temperature ~ Depth, subset(verticalSubData, Pond == pondID & Num == num))
  return(summary(tempModel))
}

tempDepthModel('T106', 1)
tempDepthModel('T108', 1)
tempDepthModel('T109', 1)
tempDepthModel('T106', 2)
tempDepthModel('T108', 2)
tempDepthModel('T109', 2)
```

```{r}
doDepthModel1 <- lm(DO ~ Depth, verticalSubData)
summary(doDepthModel1)

doDepthModel <- function(pondID,
                           num){
  tempModel <- lm(DO ~ Depth, subset(verticalSubData, Pond == pondID & Num == num))
  return(summary(tempModel))
}

doDepthModel('T106', 1)
doDepthModel('T108', 1)
doDepthModel('T109', 1)
doDepthModel('T106', 2)
doDepthModel('T108', 2)
doDepthModel('T109', 2)
```

```{r}
turbDepthModel1 <- lm(Turbidity ~ Depth, verticalSubData)
summary(turbDepthModel1)

turbDepthModel <- function(pondID,
                           num){
  tempModel <- lm(Turbidity ~ Depth, subset(verticalSubData, Pond == pondID & Num == num))
  return(summary(tempModel))
}

turbDepthModel('T106', 1)
turbDepthModel('T108', 1)
turbDepthModel('T109', 1)
turbDepthModel('T106', 2)
turbDepthModel('T108', 2)
turbDepthModel('T109', 2)
```

# Invertebrates Data

```{r}
invertData <- read.csv("EEB397_InvertData.csv")
```


```{r}
rank.abund <- function(x, num) {
  tmp <- x[num, -c(1,2)]
  tmp2 <- tmp[tmp > 0] / sum(tmp)
  tmp3 <- tmp2[order(-tmp2)]
cbind(rank = 1:length(tmp3), RA = tmp3) %>% 
  as.data.frame() %>% 
ggplot(aes(x = rank, y = RA)) +
  geom_col(colour ="blue", fill = "lightblue") +
  labs(y = "Relative Abundance", x = "Rank", title = paste("Pond", PONDS[num])) +
  ylim(0,1)
}
```

```{r}
A1 <- rank.abund(invertData, 1)
A2 <- rank.abund(invertData, 2)
A3 <- rank.abund(invertData, 3)
B1 <- rank.abund(invertData, 4)
B2 <- rank.abund(invertData, 5)
B3 <- rank.abund(invertData, 6)
A4 <- rank.abund(invertData, 7)
A5 <- rank.abund(invertData, 8)
A6 <- rank.abund(invertData, 9)
B4 <- rank.abund(invertData, 10)
B5 <- rank.abund(invertData, 11)
B6 <- rank.abund(invertData, 12)
A7 <- rank.abund(invertData, 13)
A8 <- rank.abund(invertData, 14)
A9 <- rank.abund(invertData, 15)
B7 <- rank.abund(invertData, 16)
B8 <- rank.abund(invertData, 17)
B9 <- rank.abund(invertData, 18)
```

```{r}
ggarrange(A1, A2, A3, ncol = 3) + 
  theme(plot.caption = element_text(hjust = 0)) +
  labs(caption = "Figure 2A. Rank-abundance distributions for the pond T106 site A.
")
ggsave("Plots/rankdistT106A.png")

ggarrange(A4, A5, A6, ncol = 3) + 
  theme(plot.caption = element_text(hjust = 0)) +
  labs(caption = "Figure 2B. Rank-abundance distributions for the pond T108 site A.
")
ggsave("Plots/rankdistT108A.png")

ggarrange(A7, A8, A9, ncol = 3) + 
  theme(plot.caption = element_text(hjust = 0)) +
  labs(caption = "Figure 2C. Rank-abundance distributions for the pond T109 site A.
")
ggsave("Plots/rankdistT109A.png")


ggarrange(B1, B2, B3, ncol = 3) + 
  theme(plot.caption = element_text(hjust = 0)) +
  labs(caption = "Figure 2D. Rank-abundance distributions for the pond T106 site B.
")
ggsave("Plots/rankdistT106B.png")

ggarrange(B4, B5, B6, ncol = 3) + 
  theme(plot.caption = element_text(hjust = 0)) +
  labs(caption = "Figure 2E. Rank-abundance distributions for the pond T108 site B.
")
ggsave("Plots/rankdistT108B.png")

ggarrange(B7, B8, B9, ncol = 3) + 
  theme(plot.caption = element_text(hjust = 0)) +
  labs(caption = "Figure 2F. Rank-abundance distributions for the pond T109 site B.
")
ggsave("Plots/rankdistT109B.png")
```


```{r}
invertData %>% 
  mutate(nSpecies=rowSums(.!=0) - 2) %>% 
  ggplot(aes(x = nSpecies)) +
  geom_bar(colour = "blue", fill = "lightblue") +
  theme(plot.caption = element_text(hjust = 0)) +
  labs(x = "Number of Species", y = "Frequency", title = "Frequency versus Number of Species",
       caption = "Figure 3A. Frequency distribution of number of species found in each sample (n = 18).")
ggsave("Plots/speciesdistribution.png")
```

```{r}
invertData %>% 
  mutate(nSpecies=rowSums(.!=0) - 2) %>% 
  ggplot(aes(x= nSpecies, fill = factor(depth), group = depth)) + 
    geom_bar(colour = "black", position = "stack") +
  theme(plot.caption = element_text(hjust = 0)) +
  labs(x = "Number of Species", y = "Frequency", 
       fill = "Depth (cm)",
       title = "Frequency versus Number of Species",
       caption = "Figure 3B. Frequency distribution of number of species found in each sample (n = 18), separated by depth.")
ggsave("Plots/speciesdistributionD.png")
```



```{r}
invertData %>% 
  pivot_longer(!c(pondID, depth), values_to = "total", names_to = "family") %>% 
  ggplot(aes(x=family, y = total, fill=family)) + 
         geom_bar(stat = "identity", position = "fill") + 
    theme(axis.text.x=element_blank(), 
          axis.ticks.x=element_blank(),
          axis.text.y=element_blank(), 
          axis.ticks.y=element_blank(),
          plot.caption = element_text(hjust = 0)) + 
  labs(x = "Present Taxonomic Families", y="", title = "Species Richness across Ponds.",
       fill = "Taxonomic Families",
       caption = "Figure 4A. Taxonomic families present in each sample.") + 
  guides(fill=guide_legend(ncol=2)) + 
         facet_wrap(vars(pondID), nrow = 6, ncol =3)
ggsave("Plots/familypresence.png")
```


```{r}
invertData %>% 
  pivot_longer(!c(pondID, depth), values_to = "total", names_to = "family") %>% 
  ggplot(aes(x=pondID, y = total, fill=family)) + 
         geom_bar(stat = "identity", position = "fill") + 
    theme(axis.text.x=element_text(angle = 45, hjust = 1),
          plot.caption = element_text(hjust = 0)) + 
  labs(x = "Present Taxonomic Families", y="Relative Abundance", title = "Species Richness across Ponds.",
       fill = "Taxonomic Families",
       caption = "Figure 4B. Relative abundance of taxonomic families by sample.") + 
  guides(fill=guide_legend(ncol=2))
ggsave("Plots/familyrelative.png")
```

```{r}
SR <- specnumber(invertData[,-c(1,2)])
simpInv <- diversity(invertData[,-c(1,2)], index = "invsimpson")
simpEven <- simpInv / SR
```


```{r}
brayCurtisInv <- 1 - vegdist(invertData[,-c(1,2)], method = "bray", diag = FALSE) %>% 
  as.matrix()
```


## Bray Curtis By Depth

```{r}
mod3index1 <- combinations(n = 6, r = 2, repeats.allowed = F, v = seq(1, 18, 3)) %>% 
  as.data.frame()

mod3index2 <- combinations(n = 6, r = 2, repeats.allowed = F, v = seq(2, 18, 3)) %>% 
  as.data.frame()

mod3index3 <- combinations(n = 6, r = 2, repeats.allowed = F, v = seq(3, 18, 3)) %>% 
  as.data.frame()
```


```{r}
brayByDepth <- c()
for (i in 1:length(mod3index1$V1)){
  brayByDepth <- rbind(brayByDepth, 
                       c(50, brayCurtisInv[mod3index1$V1[i], mod3index1$V2[i]]))
}


temp2 <- 0 
for (i in 1:length(mod3index2$V1)){
  brayByDepth <- rbind(brayByDepth, 
                       c(100, brayCurtisInv[mod3index2$V1[i], mod3index2$V2[i]]))
}


temp3 <- 0 
for (i in 1:length(mod3index3$V1)){
  brayByDepth <- rbind(brayByDepth, 
                       c(150, brayCurtisInv[mod3index3$V1[i], mod3index3$V2[i]]))
}

brayByDepth <- as.data.frame(brayByDepth)
colnames(brayByDepth) <- c("depth", "bcSim")
```


```{r}
brayByDepth %>% 
  ggplot(aes(x = depth, y = bcSim, group = depth)) +
  geom_boxplot() + 
  labs(x = "Depth (cm)", y = "Similarity (Bray-Curtis)", title = "Bray-Curtis Similarity versus Depth")
```


## Bray-Curtis By Pond


```{r}
ord3index1 <- combinations(n = 6, r = 2, repeats.allowed = F, v = 1:6) %>% 
  as.data.frame()

ord3index2 <- combinations(n = 6, r = 2, repeats.allowed = F, v = 7:12) %>% 
  as.data.frame()

ord3index3 <- combinations(n = 6, r = 2, repeats.allowed = F, v = 13:18) %>% 
  as.data.frame()
```

```{r}
brayByPond <- c()
for (i in 1:length(ord3index1$V1)){
  brayByPond <- rbind(brayByPond, 
                       c("T106", brayCurtisInv[ord3index1$V1[i], ord3index1$V2[i]]))
}


for (i in 1:length(ord3index2$V1)){
  brayByPond <- rbind(brayByPond, 
                       c("T108", brayCurtisInv[ord3index2$V1[i], ord3index2$V2[i]]))
}


for (i in 1:length(ord3index3$V1)){
  brayByPond <- rbind(brayByPond, 
                       c("T109", brayCurtisInv[ord3index3$V1[i], ord3index3$V2[i]]))
}

brayByPond <- as.data.frame(brayByPond)
colnames(brayByPond) <- c("pond", "bcSim")
brayByPond$bcSim <- as.numeric(brayByPond$bcSim)
```

```{r}
brayByPond %>% 
  ggplot(aes(x = pond, y = bcSim, group = pond)) +
  geom_boxplot() + 
  labs(x = "Pond", y = "Similarity (Bray-Curtis)", title = "Bray-Curtis Similarity versus Pond")
```